In [1]:
 import pandas as pd
from sqlalchemy import create_engine

In [2]:
drought_file = "Resources/Drought.csv"
drought_df = pd.read_csv(drought_file)
drought_df.head()

,releaseDate,FIPS,county,state,NONE,D0,D1,D2,D3,D4,validStart,validEnd,domStatisticFormatID
0,2016-11-01,2013,Aleutians East Borough,AK,100.0,0.0,0.0,0.0,0.0,0.0,2016-11-01,2016-11-07,1
1,2016-10-25,2013,Aleutians East Borough,AK,100.0,0.0,0.0,0.0,0.0,0.0,2016-10-25,2016-10-31,1
2,2016-10-18,2013,Aleutians East Borough,AK,100.0,0.0,0.0,0.0,0.0,0.0,2016-10-18,2016-10-24,1
3,2016-10-11,2013,Aleutians East Borough,AK,100.0,0.0,0.0,0.0,0.0,0.0,2016-10-11,2016-10-17,1
4,2016-10-04,2013,Aleutians East Borough,AK,100.0,0.0,0.0,0.0,0.0,0.0,2016-10-04,2016-10-10,1

In [40]:
#selecting only the columns with useful info
drought_cols = ["releaseDate", "county", "state", "D3", "D4"]
drought_transformed= drought_df[drought_cols].copy()

# Rename the column headers
CA_drought = drought_transformed.rename(columns={"releaseDate": "Date",
                                                          "county": "County",
                                                          "state": "State", 
                                                         "D3": "Drought Level:Extreme",
                                                         "D4":"Drought Level:Exceptional"})

CA_drought.head()

,Date,County,State,Drought Level:Extreme,Drought Level:Exceptional
0,2016-11-01,Aleutians East Borough,AK,0.0,0.0
1,2016-10-25,Aleutians East Borough,AK,0.0,0.0
2,2016-10-18,Aleutians East Borough,AK,0.0,0.0
3,2016-10-11,Aleutians East Borough,AK,0.0,0.0
4,2016-10-04,Aleutians East Borough,AK,0.0,0.0

In [45]:
#clean up by county, and interested in Los Angeles, San Francisco, San Diego, Sacramento
CA_drought_by_county = CA_drought.loc[(CA_drought["County"] == "Los Angeles County") | (CA_drought["County"] == "San Francisco County") | (CA_drought["County"] == "Sacramento County") | (CA_drought["County"] == "San Diego County")]
CA_drought_by_county = CA_drought_by_county.reset_index(drop=True)
CA_drought_by_county.head(50)

,index,Date,County,State,Drought Level:Extreme,Drought Level:Exceptional
0,8888,2016-11-01,Los Angeles County,CA,100.0,85.59
1,8889,2016-10-25,Los Angeles County,CA,100.0,85.59
2,8890,2016-10-18,Los Angeles County,CA,100.0,85.59
3,8891,2016-10-11,Los Angeles County,CA,100.0,85.59
4,8892,2016-10-04,Los Angeles County,CA,100.0,85.59
5,8893,2016-09-27,Los Angeles County,CA,100.0,85.59
6,8894,2016-09-20,Los Angeles County,CA,100.0,85.59
7,8895,2016-09-13,Los Angeles County,CA,100.0,85.59
8,8896,2016-09-06,Los Angeles County,CA,100.0,85.59
9,8897,2016-08-30,Los Angeles County,CA,100.0,85.59
10,8898,2016-08-23,Los Angeles County,CA,100.0,85.59
11,8899,2016-08-16,Los Angeles County,CA,100.0,85.59
12,8900,2016-08-09,Los Angeles County,CA,100.0,85.59
13,8901,2016-08-02,Los Angeles County,CA,100.0,85.59
14,8902,2016-07-26,Los Angeles County,CA,100.0,85.59
15,8903,2016-07-19,Los Angeles County,CA,100.0,85.59
16,8904,2016-07-12,Los Angeles County,CA,100.0,85.59
17,8905,2016-07-05,Los Angeles County,CA,100.0,85.59
18,8906,2016-06-28,Los Angeles County,CA,100.0,85.59
19,8907,2016-06-21,Los Angeles County,CA,100.0,85.59
20,8908,2016-06-14,Los Angeles County,CA,100.0,85.59
21,8909,2016-06-07,Los Angeles County,CA,100.0,85.59
22,8910,2016-05-31,Los Angeles County,CA,100.0,85.59
23,8911,2016-05-24,Los Angeles County,CA,100.0,85.59
24,8912,2016-05-17,Los Angeles County,CA,100.0,85.59
25,8913,2016-05-10,Los Angeles County,CA,100.0,85.59
26,8914,2016-05-03,Los Angeles County,CA,100.0,85.59
27,8915,2016-04-26,Los Angeles County,CA,100.0,85.59
28,8916,2016-04-19,Los Angeles County,CA,100.0,85.59
29,8917,2016-04-12,Los Angeles County,CA,100.0,86.33
30,8918,2016-04-05,Los Angeles County,CA,100.0,86.33
31,8919,2016-03-29,Los Angeles County,CA,100.0,86.33
32,8920,2016-03-22,Los Angeles County,CA,100.0,86.33
33,8921,2016-03-15,Los Angeles County,CA,100.0,86.33
34,8922,2016-03-08,Los Angeles County,CA,100.0,86.33
35,8923,2016-03-01,Los Angeles County,CA,100.0,86.33
36,8924,2016-02-23,Los Angeles County,CA,100.0,86.33
37,8925,2016-02-16,Los Angeles County,CA,100.0,86.33
38,8926,2016-02-09,Los Angeles County,CA,100.0,86.33
39,8927,2016-02-02,Los Angeles County,CA,100.0,86.33
40,8928,2016-01-26,Los Angeles County,CA,100.0,87.92
41,8929,2016-01-19,Los Angeles County,CA,100.0,87.92
42,8930,2016-01-12,Los Angeles County,CA,100.0,87.92
43,8931,2016-01-05,Los Angeles County,CA,100.0,87.92
44,9548,2016-11-01,Sacramento County,CA,0.0,0.00
45,9549,2016-10-25,Sacramento County,CA,0.0,0.00
46,9550,2016-10-18,Sacramento County,CA,0.0,0.00
47,9551,2016-10-11,Sacramento County,CA,0.0,0.00
48,9552,2016-10-04,Sacramento County,CA,0.0,0.00
49,9553,2016-09-27,Sacramento County,CA,0.0,0.00

In [28]:
#  connection_string = "postgres:postgres@localhost:5432/customer_db"
# engine = create_engine(f'postgresql://{connection_string}')

In [29]:
# # Confirm tables
# engine.table_names()

In [30]:
# premise_transformed.to_sql(name='premise', con=engine, if_exists='append', index=True)

In [ ]:
# county_transformed.to_sql(name='county', con=engine, if_exists='append', index=True)