In [1]:
import pandas as pd
import numpy as np

file_to_load = "Output/weather.csv"

CAweather_df = pd.read_csv(file_to_load)
CAweather_df.head()

,EventId,Type,Severity,StartTime(UTC),EndTime(UTC),TimeZone,AirportCode,LocationLat,LocationLng,City,County,State,ZipCode
0,W-68940,Fog,Moderate,2016-01-02 00:53:00,2016-01-02 01:53:00,US/Pacific,KWVI,36.9394,-121.79,Freedom,Santa Cruz,CA,95019.0
1,W-68941,Rain,Light,2016-01-04 02:53:00,2016-01-04 05:53:00,US/Pacific,KWVI,36.9394,-121.79,Freedom,Santa Cruz,CA,95019.0
2,W-68942,Rain,Light,2016-01-04 11:53:00,2016-01-04 17:53:00,US/Pacific,KWVI,36.9394,-121.79,Freedom,Santa Cruz,CA,95019.0
3,W-68943,Rain,Light,2016-01-05 06:53:00,2016-01-05 12:48:00,US/Pacific,KWVI,36.9394,-121.79,Freedom,Santa Cruz,CA,95019.0
4,W-68944,Rain,Moderate,2016-01-05 12:48:00,2016-01-05 13:50:00,US/Pacific,KWVI,36.9394,-121.79,Freedom,Santa Cruz,CA,95019.0

In [2]:
CAweather_df = CAweather_df[["Severity","EndTime(UTC)","County","State"]]
CAweather_df

        Severity         EndTime(UTC)      County State
0       Moderate  2016-01-02 01:53:00  Santa Cruz    CA
1          Light  2016-01-04 05:53:00  Santa Cruz    CA
2          Light  2016-01-04 17:53:00  Santa Cruz    CA
3          Light  2016-01-05 12:48:00  Santa Cruz    CA
4       Moderate  2016-01-05 13:50:00  Santa Cruz    CA
...          ...                  ...         ...   ...
201831    Severe  2019-11-28 04:55:00    Humboldt    CA
201832       UNK  2019-12-07 01:15:00    Humboldt    CA
201833       UNK  2019-12-07 02:15:00    Humboldt    CA
201834       UNK  2019-12-07 11:15:00    Humboldt    CA
201835       UNK  2019-12-29 19:15:00    Humboldt    CA

[201836 rows x 4 columns]

In [3]:
CAweather_df.columns=[["Severity","Date","County", "State"]]
CAweather_df.head()

   Severity                 Date      County State
0  Moderate  2016-01-02 01:53:00  Santa Cruz    CA
1     Light  2016-01-04 05:53:00  Santa Cruz    CA
2     Light  2016-01-04 17:53:00  Santa Cruz    CA
3     Light  2016-01-05 12:48:00  Santa Cruz    CA
4  Moderate  2016-01-05 13:50:00  Santa Cruz    CA

In [4]:
CAweather_df_by_county = CAweather_df.loc[(CAweather_df["County"] == "Los Angeles") | (CAweather_df["County"] == "San Diego") |
                                         (CAweather_df["County"] == "Sacramento")]
CAweather_df_by_county.head()

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
Avocado_weather = "Resources/Avocado_weather(clean).csv"
CAweather_df.to_csv(Avocado_weather,index=False)

In [ ]:
# connection_string = "postgres:postgres@localhost:5432/customer_db"
# engine = create_engine(f'postgresql://{connection_string}')

In [ ]:
# engine.table_names()

In [ ]:
# premise_transformed.to_sql(name='premise', con=engine, if_exists='append', index=True)

In [ ]:
# county_transformed.to_sql(name='county', con=engine, if_exists='append', index=True)